---
title: "Mini Project 4"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(RMySQL)
library(leaflet)
db <- dbConnect(MySQL(),
                host = "scidb.smith.edu",
                user = "mth292",
                password = "RememberPi",
                dbname = "citibike") 
```

```{r}
library(tidyverse)
  library(RMySQL)
  db <- dbConnect(MySQL(), 
                  host = "scidb.smith.edu", 
                  user = "mth292", 
                  password = "RememberPi", 
                  dbname = "citibike")
  knitr::opts_chunk$set(connection = db, max.print = 20)

```

```{sql connection= db, output.var = "biking"}
SELECT *
FROM trips 
WHERE stop_time LIKE '%2017-11-22 %'

```

```{r}
demographic_bike <- db%>%
  dbGetQuery("SELECT *
FROM trips 
WHERE stop_time LIKE '%2017-11-22 %'
AND birth_year IS NOT NULL
")

```



```{r}
demographic_bike %>%
ggplot(aes(stop_time, birth_year, col = "blue")) +
  geom_point(alpha = 0.1, )+ 
  xlab("Time of Day")+
  ylab("Birth Year")

```


```{r}
#Making Amrita icon to show where she got bike 17321!
Amrita <-makeIcon(iconUrl = ("http://i67.tinypic.com/ngq4ah.jpg" ), iconWidth = 35, iconHeight = 40) 
```

```{r}
#Making bike icon for other stops
Bike_Icon <- makeIcon(iconUrl = ("http://icons.iconarchive.com/icons/fasticon/ifunny-vol-2/128/bike-icon.png"), iconWidth = 35, iconHeight = 40)
```


```{r}
#adding locations bike 17321 docked at on November 22nd, 2017
leaflet()%>%
  addTiles()%>%
  addMarkers(lng = -73.99392888, lat = 40.76727216, popup = "First Stop", icon = Bike_Icon)%>% 
  addMarkers(lng = -73.9845272898674, lat = 40.76068327096592, popup= "Second Stop", icon = Bike_Icon)%>% 
  addMarkers(lng = -73.96409422159195, lat = 40.77118287540658, popup= "Third Stop", icon = Bike_Icon)%>%
  addMarkers(lng = -73.97109243, lat = 40.76350532, popup= "Fourth Stop", icon = Bike_Icon)%>%
  addMarkers(lng = -73.97282625, lat = 40.75255434, popup= "Fifth Stop", icon = Bike_Icon)%>%
  addMarkers(lng = -73.95818491, lat = 40.76500525, popup= "Sixth Stop (AMRITA!)", icon = Amrita)%>%
  addMarkers(lng = -73.96222088, lat = 40.773763, popup= "Seventh Stop", icon = Bike_Icon)%>%
  addMarkers(lng = -73.98490707, lat = 40.74765947, popup= "Eighth Stop", icon = Bike_Icon)
 
```


```{r}
